/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg2.edd;

import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author a-utr
 */
public class Interfaz extends javax.swing.JFrame {

    TablaHash tabla = new TablaHash(101);
    TablaHash tablaPalabrasClave = new TablaHash(100); 
    ArbolAVLPalabras arbolAVL = new ArbolAVLPalabras();
    ArbolAVLAutores arbolAVLa = new ArbolAVLAutores();

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnBuscarPalabra = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        btnAnalizar1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnBuscarAutor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 224, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 280));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 450, 320));

        jPanel4.setBackground(new java.awt.Color(204, 224, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnListar.setFont(new java.awt.Font("Baloo Bhai", 0, 12)); // NOI18N
        btnListar.setForeground(new java.awt.Color(0, 51, 153));
        btnListar.setText("Listar Palabras Claves");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel4.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, 50));

        jPanel6.setBackground(new java.awt.Color(204, 224, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setFont(new java.awt.Font("Baloo Bhai", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 51, 153));
        btnAgregar.setText("Agregar Resumen");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel6.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 50));

        jLabel4.setBackground(new java.awt.Color(0, 0, 102));
        jLabel4.setFont(new java.awt.Font("Baloo Bhai", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(13, 50, 140));
        jLabel4.setText("¡ BIENVENIDO !");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jPanel7.setBackground(new java.awt.Color(204, 224, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarPalabra.setFont(new java.awt.Font("Baloo Bhai", 0, 12)); // NOI18N
        btnBuscarPalabra.setForeground(new java.awt.Color(0, 51, 153));
        btnBuscarPalabra.setText("Buscar por Palabra Clave");
        btnBuscarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPalabraActionPerformed(evt);
            }
        });
        jPanel7.add(btnBuscarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, 50));

        jSeparator2.setForeground(new java.awt.Color(0, 51, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 690, 20));

        jPanel8.setBackground(new java.awt.Color(204, 224, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAnalizar1.setFont(new java.awt.Font("Baloo Bhai", 0, 12)); // NOI18N
        btnAnalizar1.setForeground(new java.awt.Color(0, 51, 153));
        btnAnalizar1.setText("Analizar Resumen");
        btnAnalizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizar1ActionPerformed(evt);
            }
        });
        jPanel8.add(btnAnalizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 50));

        jPanel9.setBackground(new java.awt.Color(204, 224, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarAutor.setFont(new java.awt.Font("Baloo Bhai", 0, 12)); // NOI18N
        btnBuscarAutor.setForeground(new java.awt.Color(0, 51, 153));
        btnBuscarAutor.setText("Buscar por Autor");
        btnBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAutorActionPerformed(evt);
            }
        });
        jPanel9.add(btnBuscarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 200, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo5.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar Archivo de Resumen");       
        FileNameExtensionFilter filtroTexto = new FileNameExtensionFilter("Archivos de Texto (*.txt)", "txt");
        fileChooser.setFileFilter(filtroTexto);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int resultado = fileChooser.showOpenDialog(this); 

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            
        try {
            java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(archivoSeleccionado));
            String linea;

            String titulo = "";
            String autores = "";
            String resumenCuerpo = "";
            String palabrasClaves = "";

            int seccionActual = 0; 

            while ((linea = br.readLine()) != null) {
                linea = linea.trim(); 
                
                if (linea.isEmpty()) continue; 
                if (linea.equalsIgnoreCase("Autores")) {
                    seccionActual = 1;
                    continue; 
                }
                
                if (linea.equalsIgnoreCase("Resumen")) {
                    seccionActual = 2;
                    continue; 
                }
                if (linea.toLowerCase().startsWith("palabras claves")) {
                    if (linea.contains(":")) {
                        palabrasClaves = linea.substring(linea.indexOf(":") + 1).trim();
                    }
                    continue; 
                }

                switch (seccionActual) {
                    case 0: 
                        titulo += linea + " "; 
                        break;
                    case 1: 
                        autores += linea + "\n"; 
                        break;
                    case 2:
                        resumenCuerpo += linea + " ";
                        break;
                }
            }
            br.close();

            titulo = titulo.trim();
            autores = autores.trim();
            resumenCuerpo = resumenCuerpo.trim();

            if (!titulo.isEmpty()) {

                Resumen nuevoResumen = new Resumen(titulo, autores, resumenCuerpo, palabrasClaves);

                boolean guardado = tabla.AgregarElem(nuevoResumen);
                
                if (guardado) {
                    if (palabrasClaves != null && !palabrasClaves.isEmpty()) {

        if (palabrasClaves.endsWith(".")) {
            palabrasClaves = palabrasClaves.substring(0, palabrasClaves.length() - 1);
        }

        String[] listaFrases = palabrasClaves.split(",");

        String cuerpoLimpio = resumenCuerpo.toLowerCase().replaceAll("[^a-z0-9]", "");

        for (String frase : listaFrases) {
            
            String fraseOriginal = frase.trim(); 

            String fraseParaBuscar = fraseOriginal.toLowerCase().replaceAll("[^a-z0-9#\\+]", "");
            
            if (fraseParaBuscar.length() >= 1) {
                int contador = 0;
                int indice = 0;

                while ((indice = cuerpoLimpio.indexOf(fraseParaBuscar, indice)) != -1) {
                    contador++;
                    indice += fraseParaBuscar.length();
                }

                if (contador > 0) {
                    for (int i = 0; i < contador; i++) {
                        arbolAVL.insertarOActualizar(fraseOriginal, titulo);
                    }
                } else {
                    arbolAVL.insertarOActualizar(fraseOriginal, titulo);
                    arbolAVL.fijarFrecuenciaEnCero(fraseOriginal, titulo);
                }
                Object resultadoHash = tablaPalabrasClave.buscar(fraseOriginal);
    ListaEnlazada listaAsociada;

    if (resultadoHash == null) {
        listaAsociada = new ListaEnlazada();
        tablaPalabrasClave.insertar(fraseOriginal, listaAsociada);
    } else {
        listaAsociada = (ListaEnlazada) resultadoHash;
    }

    if (!listaAsociada.buscar(titulo)) {
        listaAsociada.agregar(titulo);
    }
            }
        }
    }
                    if (autores != null && !autores.isEmpty()) {
                    String[] listaAutores = autores.split("\n");

                        for (String nombreAutor : listaAutores) {
                            String nombreLimpio = normalizarNombre(nombreAutor);

                                if (nombreLimpio.length() > 0) {
                                arbolAVLa.insertarAutor(nombreLimpio, titulo);
                            }
    }
}
                    javax.swing.JOptionPane.showMessageDialog(this, "Resumen cargado\nTítulo: " + titulo);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error: Ese resumen ya existe en la base de datos.");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: No se pudo identificar el título del resumen.");
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
        }
       }
       
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAnalizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizar1ActionPerformed
String[] titulos = tabla.obtenerTitulos();
    
    if (titulos.length == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay investigaciones guardadas");
        return;
    }

    java.util.Arrays.sort(titulos);

    String tituloSeleccionado = (String) javax.swing.JOptionPane.showInputDialog(
            this, 
            "Seleccione una investigación para analizar:", 
            "Analizar Resumen", 
            javax.swing.JOptionPane.QUESTION_MESSAGE, 
            null, 
            titulos, 
            titulos[0]);

    if (tituloSeleccionado != null) {
        DetallesResumen(tituloSeleccionado);
    }
    }//GEN-LAST:event_btnAnalizar1ActionPerformed

    private void btnBuscarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPalabraActionPerformed
        String palabraBuscada = javax.swing.JOptionPane.showInputDialog(
            this, 
            "Ingrese la palabra clave a buscar:", 
            "Buscar Investigaciones por Palabra Clave", 
            javax.swing.JOptionPane.QUESTION_MESSAGE);

    if (palabraBuscada == null || palabraBuscada.trim().isEmpty()) return;

    palabraBuscada = palabraBuscada.trim();

    Object resultado = tablaPalabrasClave.buscar(palabraBuscada);

    if (resultado != null) {
        ListaEnlazada listaTitulos = (ListaEnlazada) resultado;
        
        if (!listaTitulos.estaVacia()) {

            int cantidad = listaTitulos.getTamano();
            String[] titulosArray = new String[cantidad];
            
            NodoLista actual = listaTitulos.getCabeza();
            int i = 0;
            while(actual != null) {
                titulosArray[i] = (String) actual.getDato();
                actual = actual.getSig();
                i++;
            }
            // -----------------------------------------------------

            String tituloSeleccionado = "";

            if (cantidad > 1) {
                tituloSeleccionado = (String) javax.swing.JOptionPane.showInputDialog(
                    this,
                    "La palabra '" + palabraBuscada + "' aparece en " + cantidad + " investigaciones.\nSeleccione una:",
                    "Resultados de Búsqueda",
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    titulosArray,
                    titulosArray[0]);
            } else {
                tituloSeleccionado = titulosArray[0];
            }
            if (tituloSeleccionado != null) {
                DetallesResumen(tituloSeleccionado);
            }

        } else {
             javax.swing.JOptionPane.showMessageDialog(this, "La palabra existe pero no tiene investigaciones asociadas (Error extraño).");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron investigaciones con la palabra clave: " + palabraBuscada);
    }
    }//GEN-LAST:event_btnBuscarPalabraActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
ListaEnlazada listaDeNodos = arbolAVL.obtenerListaOrdenada();

    if (listaDeNodos.getCabeza() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "El árbol está vacío. Agregue resúmenes primero");
        return;
    }

    java.util.ArrayList<String> listaNombres = new java.util.ArrayList<>();
    java.util.ArrayList<PalabraClaveNodo> listaObjetos = new java.util.ArrayList<>();

    NodoLista actual = listaDeNodos.getCabeza();
    while (actual != null) {
        PalabraClaveNodo nodo = (PalabraClaveNodo) actual.getDato();
        
        listaNombres.add(nodo.getPalabraClave()); 
        listaObjetos.add(nodo);                 
        
        actual = actual.getSig();
    }

    Object[] opciones = listaNombres.toArray();

    String seleccion = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Seleccione una palabra para ver sus detalles:",
            "Palabras Claves",
            javax.swing.JOptionPane.PLAIN_MESSAGE,
            null,
            opciones,          
            opciones[0]         
    );

    if (seleccion != null) {

        int indice = listaNombres.indexOf(seleccion);
        PalabraClaveNodo nodoElegido = listaObjetos.get(indice);

        mostrarDetalles(nodoElegido);
     }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAutorActionPerformed
        String[] listaAutores = arbolAVLa.obtenerAutoresOrdenados(); 

    if (listaAutores == null || listaAutores.length == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay autores registrados");
        return;
    }
    String autorSeleccionado = (String) javax.swing.JOptionPane.showInputDialog(
            this,
            "Seleccione un autor para ver sus trabajos:",
            "Búsqueda por Autor",
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            listaAutores,
            listaAutores[0]);

    if (autorSeleccionado == null) return;
    ListaEnlazada resultados = arbolAVLa.buscarInvestigacionesDe(autorSeleccionado);

    if (resultados != null && !resultados.estaVacia()) { 

        int cantidad = resultados.getTamano(); 
        String[] titulosArray = new String[cantidad];
        
        NodoLista actual = resultados.getCabeza(); 
        int i = 0;
        
        while(actual != null) {
            titulosArray[i] = (String) actual.getDato(); 
            actual = actual.getSig(); 
            i++;
        }
        String tituloAAnalizar = "";

        if (cantidad > 1) {
            tituloAAnalizar = (String) javax.swing.JOptionPane.showInputDialog(
                this,
                "El autor " + autorSeleccionado + " participa en varias investigaciones.\nSeleccione una:",
                "Seleccionar Investigación",
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                titulosArray, 
                titulosArray[0]);
        } else {
            tituloAAnalizar = titulosArray[0];
        }

        if (tituloAAnalizar != null) {
            DetallesResumen(tituloAAnalizar);
        }

    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: No se encontraron investigaciones para este autor.");
    }
    }//GEN-LAST:event_btnBuscarAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    private void DetallesResumen(String tituloBuscado) {
    if (tituloBuscado == null) return;

    Resumen resumen = tabla.BuscarElem(tituloBuscado);
    
    if (resumen != null) {
        StringBuilder sb = new StringBuilder();

        sb.append("Nombre del trabajo:\n").append(resumen.getTitulo()).append("\n\n");
        sb.append("Autores:\n").append(resumen.getAutores()).append("\n\n");
        sb.append("Palabras clave:\n");

        String[] listaClaves = resumen.getPclaves().split(",");

        for (String palabra : listaClaves) {
            String palabraOriginal = palabra.trim();
            
            if (!palabraOriginal.isEmpty()) {
                int frecuencia = contarFrecuencia(resumen.getResumen(), palabraOriginal);

                sb.append("• ").append(palabraOriginal)
                  .append(": ").append(frecuencia).append("\n");
            }
        }

        jTextArea1.setText(sb.toString());
        
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: No se pudo recuperar la información del resumen.");
    }
}
    
    private int contarFrecuencia(String textoCompleto, String palabraOriginal) {
    if (textoCompleto == null || palabraOriginal == null) return 0;

    String cuerpoLimpio = textoCompleto.toLowerCase().replaceAll("[^a-z0-9#\\+]", "");
    String palabraParaBuscar = palabraOriginal.toLowerCase().replaceAll("[^a-z0-9#\\+]", "");
    
    if (palabraParaBuscar.isEmpty()) return 0;

    int contador = 0;
    int indice = 0;

    while ((indice = cuerpoLimpio.indexOf(palabraParaBuscar, indice)) != -1) {
        contador++;
        indice += palabraParaBuscar.length(); 
    }
    
    return contador;
    }
    
    private String normalizarNombre(String nombre) {
    if (nombre == null) return "";

    String limpio = nombre.replace("-", " ");
    limpio = limpio.replaceAll("[\\n\\r\\t]", " ");
    limpio = limpio.replace("\u00A0", " ");
    limpio = limpio.replaceAll("\\s+", " ").trim();
    
    return limpio;
}
    
    private void mostrarDetalles(PalabraClaveNodo nodo) {
    if (nodo == null) return;

    StringBuilder sb = new StringBuilder();
    sb.append("Palabra Clave: ").append(nodo.getPalabraClave()).append("\n");
    sb.append("--------------------------------------------\n");

    ListaEnlazada listaFrecuencias = nodo.getArticulosFrecuenciaList();
    
    if (listaFrecuencias != null) {
        NodoLista actual = listaFrecuencias.getCabeza();
        int total = 0;

        while (actual != null) {
            if (actual.getDato() instanceof ArticuloFrecuencia) {
                ArticuloFrecuencia af = (ArticuloFrecuencia) actual.getDato();
                sb.append(" • Resumen: ").append(af.getClaveResumen())
                  .append("  |  Cant: ").append(af.getFrecuencia()).append("\n");
                total += af.getFrecuencia();
            }
            actual = actual.getSig();
        }
        sb.append("\nTOTAL APARICIONES: ").append(total);
    } else {
        sb.append("No hay datos de frecuencia.");
    }

    javax.swing.JOptionPane.showMessageDialog(this, sb.toString(), "Detalles de Palabra", javax.swing.JOptionPane.INFORMATION_MESSAGE);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnalizar1;
    private javax.swing.JButton btnBuscarAutor;
    private javax.swing.JButton btnBuscarPalabra;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}